# Generated by Django 4.1.5 on 2023-02-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingaccount',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
