# Generated by Django 4.1.5 on 2023-02-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0002_alter_listingaccount_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingaccount',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listingaccount',
            name='account_type',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('homeowner', 'Homeowner')], max_length=30, null=True),
        ),
    ]
