# Generated by Django 4.1.5 on 2023-01-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0002_rename_tenant_listingaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests_gardening', models.BooleanField(null=True)),
                ('interests_cooking', models.BooleanField(null=True)),
                ('interests_hiking', models.BooleanField(null=True)),
                ('interests_music', models.BooleanField(null=True)),
                ('interests_reading', models.BooleanField(null=True)),
                ('interests_art', models.BooleanField(null=True)),
                ('interests_puzzles', models.BooleanField(null=True)),
                ('interests_sports', models.BooleanField(null=True)),
                ('interests_yoga', models.BooleanField(null=True)),
                ('interests_cars', models.BooleanField(null=True)),
                ('interests_other', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extroverted', models.BooleanField(null=True)),
                ('outgoing', models.BooleanField(null=True)),
                ('introverted', models.BooleanField(null=True)),
                ('open', models.BooleanField(null=True)),
                ('creative', models.BooleanField(null=True)),
                ('analytical', models.BooleanField(null=True)),
                ('feeling', models.BooleanField(null=True)),
                ('passive', models.BooleanField(null=True)),
                ('quiet', models.BooleanField(null=True)),
                ('adventurous', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listingaccount',
            name='name',
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='age_range',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='date_of_birth',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='occupation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='tell_us_about_yourself',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='interests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listingAccount.interests'),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='personal_traits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listingAccount.personaltraits'),
        ),
    ]
