# Generated by Django 4.1.5 on 2023-01-13 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0003_interests_personaltraits_remove_listingaccount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='interests_art',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_cars',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_cooking',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_gardening',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_hiking',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_music',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_other',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_puzzles',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_reading',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_sports',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='interests_yoga',
        ),
        migrations.RemoveField(
            model_name='listingaccount',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='listingaccount',
            name='personal_traits',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='adventurous',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='analytical',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='creative',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='extroverted',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='feeling',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='introverted',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='open',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='outgoing',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='passive',
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='quiet',
        ),
        migrations.AddField(
            model_name='interests',
            name='interests',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interests',
            name='listing_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listingAccount.listingaccount'),
        ),
        migrations.AddField(
            model_name='personaltraits',
            name='listing_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listingAccount.listingaccount'),
        ),
        migrations.AddField(
            model_name='personaltraits',
            name='traits',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
