# Generated by Django 4.1.5 on 2023-02-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0003_listingaccount_age_alter_listingaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingaccount',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
