# Generated by Django 4.1.5 on 2023-02-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0004_alter_listingaccount_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingaccount',
            name='age',
        ),
    ]
