# Generated by Django 4.0.3 on 2023-01-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0004_remove_interests_interests_art_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=200, null=True)),
                ('listing_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='listingAccount.listingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=200, null=True)),
                ('listing_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_traits', to='listingAccount.listingaccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='personaltraits',
            name='listing_account',
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.DeleteModel(
            name='PersonalTraits',
        ),
    ]
