# Generated by Django 4.0.3 on 2023-01-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0005_interest_personaltrait_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingaccount',
            old_name='occupation',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='listingaccount',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='phone_number',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
