# Generated by Django 4.1.5 on 2023-02-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0005_remove_listingaccount_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lifestyle',
        ),
    ]
