# Generated by Django 4.0.3 on 2023-01-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0006_rename_occupation_listingaccount_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingaccount',
            name='data_of_birth',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
