# Generated by Django 4.0.3 on 2023-01-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0007_listingaccount_data_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingaccount',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
