# Generated by Django 4.0.3 on 2023-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0008_rename_data_of_birth_listingaccount_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingaccount',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
