# Generated by Django 4.1.5 on 2023-01-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0010_listingaccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltrait',
            name='listing_account',
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='interests',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='personal_traits',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='PersonalTrait',
        ),
    ]
