# Generated by Django 4.1.5 on 2023-01-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0011_remove_personaltrait_listing_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingaccount',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='listingaccount',
            name='personal_traits',
        ),
        migrations.RemoveField(
            model_name='listingaccount',
            name='username',
        ),
        migrations.CreateModel(
            name='PersonalTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=200, null=True)),
                ('listing_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_traits', to='listingAccount.listingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=200, null=True)),
                ('listing_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='listingAccount.listingaccount')),
            ],
        ),
    ]
