# Generated by Django 4.1.5 on 2023-01-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0011_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='favorites',
            new_name='favorite',
        ),
    ]
