# Generated by Django 4.1.5 on 2023-01-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0012_remove_listingaccount_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingaccount',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
