# Generated by Django 4.1.5 on 2023-01-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0012_rename_favorites_favorites_favorite'),
        ('listingAccount', '0013_listingaccount_username'),
    ]

    operations = [
    ]
