# Generated by Django 4.1.5 on 2023-01-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0014_merge_20230126_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingaccount',
            name='banner_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='display_picture_four',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='display_picture_one',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='display_picture_three',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='display_picture_two',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listingaccount',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
