# Generated by Django 4.1.5 on 2023-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0015_listingaccount_banner_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorite',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
