# Generated by Django 4.1.5 on 2023-02-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0017_accountevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='listing_account',
        ),
        migrations.RemoveField(
            model_name='listingaccount',
            name='created',
        ),
        migrations.DeleteModel(
            name='AccountEvents',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
