# Generated by Django 4.1.5 on 2023-02-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountEvents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountevents',
            old_name='accountEvents',
            new_name='accountEvent',
        ),
    ]
