# Generated by Django 4.1.5 on 2023-02-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_favorites_property_id'),
        ('propertyListing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyListing',
        ),
    ]
