# Generated by Django 4.1.5 on 2023-03-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyListing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='listing_image_four',
            field=models.ImageField(null=True, upload_to='listing_image_four/'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='listing_image_three',
            field=models.ImageField(null=True, upload_to='listing_image_three/'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='listing_image_two',
            field=models.ImageField(null=True, upload_to='listing_image_two/'),
        ),
    ]
