# Generated by Django 4.1.5 on 2023-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyListing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='listing_bathrooms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='listing_bedrooms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='listing_housemates',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='listing_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
