# Generated by Django 4.1.5 on 2023-02-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housemate', '0002_delete_housemate'),
        ('favorites', '0002_delete_favorites'),
        ('propertyListing', '0002_listingutilities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingUtilities',
        ),
        migrations.DeleteModel(
            name='PropertyListing',
        ),
    ]
