# Generated by Django 4.1.5 on 2023-02-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyListing', '0002_listingutilities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingUtilities',
        ),
    ]
