# Generated by Django 4.1.5 on 2023-02-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyListing', '0003_delete_listingutilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingUtilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_utility', models.CharField(max_length=200, null=True)),
                ('property_listing_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_utilities', to='propertyListing.propertylisting')),
            ],
        ),
    ]
