# Generated by Django 4.1.5 on 2023-02-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyListing', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='listing_women_homeowner',
            field=models.BooleanField(null=True),
        ),
    ]
