# Generated by Django 4.1.5 on 2023-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyListing', '0005_propertylisting_listing_women_homeowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='listing_den',
            field=models.BooleanField(null=True),
        ),
    ]
