# Generated by Django 4.1.5 on 2023-01-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_going',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_interested',
            field=models.IntegerField(null=True),
        ),
    ]
