# Generated by Django 4.1.5 on 2023-01-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_event_going_events_event_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_going',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_interested',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
