# Generated by Django 4.1.5 on 2023-01-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
