# Generated by Django 4.1.5 on 2023-01-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0013_listingaccount_username'),
        ('notifications', '0002_alter_notifications_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='listing_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listingAccount.listingaccount'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='link',
            field=models.URLField(max_length=128, null=True),
        ),
    ]
