# Generated by Django 4.1.5 on 2023-02-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housemate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Housemate',
        ),
    ]
