# Generated by Django 4.1.5 on 2023-03-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listingAccount', '0017_accountevents'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listingAccount.listingaccount'),
        ),
    ]
