# Generated by Django 4.1.5 on 2023-03-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_listing_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listing_account',
        ),
    ]
