# Generated by Django 4.1.5 on 2023-02-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyListing', '0003_initial'),
        ('favorites', '0002_remove_favorites_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='property_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyListing.propertylisting'),
        ),
    ]
